server:
  port: 8080

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/atlanticodb
    username: root
    password: atlanticoapi@2021
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: atlanticoapi@2021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
